modLoader = "javafml" #mandatory
loaderVersion = "[46,)" #mandatory This is typically bumped every Minecraft version by Forge.
license = "MIT"
[[mods]] #mandatory
modId = "vapourware" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "VapourWare" #mandatory
credits = "Thanks goes to everyone who has contributed to the global modding knowledge database, MCJTY, Kaupenjoe, and TheGreyGhost for tutorials/resources" #optional
authors = "VapourDrive" #optional
description = '''
This mod contains the building blocks for my other mods... and a wrench
'''
[[dependencies.vapourware]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,)" #mandatory
ordering = "NONE"
side = "BOTH"

